# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f8e7926e00f6857d91bed3796e1a6a6c244884b84bd222b38edb174fac3d62228408d191c45fdfa5e667c1636fb98a50970c2ac7e81b0086f808705cb662b47

test:
  secret_key_base: 090076022f6ad15988f14df937925de0ceb819a4ee20784e9b2467952c792764cbbce9fb3060ae5db612605641cd1ddc412636f221d449a93c0b0ec01edfecf6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
